### ISSUE TITLE
not find com.zhouzifei:simpleCache

### ISSUE THREAD

**Issue by liuzhiyuan0502** [JackySoft/marsview-backend#4]
你好！请问下，com.zhouzifei:simpleCache：1.0-SNAPSHOT jar包再那里下载呢？maven仓库找不到改组件

**Comment by yangshare** [comment]
update代码即可解决，最新引用如pom.xml
![image](https://github.com/user-attachments/assets/19932693-5dc8-4344-802c-365363555222)

**Comment by yangshare** [comment]
进一步排查找到问题，解决方式升级依赖到1.0.6
<dependency>
      <groupId>io.github.yangshare</groupId>
      <artifactId>simpleFS</artifactId>
      <version>1.0.6</version>      
    </dependency>

**Comment by liuzhiyuan0502** [comment]
收到，感谢
